#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
# Generate litellm_config.yaml from .env
# ═══════════════════════════════════════════════════════════════════════
# Called automatically by `make dev`. Reads LLM_PROVIDER and LLM_MODEL
# from .env and writes the LiteLLM proxy config.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
OUTPUT="$PROJECT_ROOT/litellm_config.yaml"

# ── Load .env ────────────────────────────────────────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: .env file not found at $ENV_FILE"
  echo "  Run: cp .env.example .env  and fill in your API key."
  exit 1
fi

# Source .env (skip comments and empty lines)
set -a
while IFS='=' read -r key value; do
  # Skip comments and empty lines
  [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
  # Trim whitespace
  key=$(echo "$key" | xargs)
  value=$(echo "$value" | xargs)
  [[ -n "$key" ]] && export "$key"="$value"
done < "$ENV_FILE"
set +a

# ── Validate required vars ──────────────────────────────────────────
LLM_PROVIDER="${LLM_PROVIDER:-}"
LLM_MODEL="${LLM_MODEL:-}"

if [[ -z "$LLM_PROVIDER" ]]; then
  echo "ERROR: LLM_PROVIDER is not set in .env"
  echo "  Supported providers: nvidia, openrouter"
  exit 1
fi

if [[ -z "$LLM_MODEL" ]]; then
  echo "ERROR: LLM_MODEL is not set in .env"
  exit 1
fi

# ── Map provider to API key env var ─────────────────────────────────
case "$LLM_PROVIDER" in
  nvidia)
    API_KEY_VAR="NVIDIA_API_KEY"
    ;;
  openrouter)
    API_KEY_VAR="OPENROUTER_API_KEY"
    ;;
  *)
    echo "ERROR: Unsupported LLM_PROVIDER='$LLM_PROVIDER'"
    echo "  Supported providers: nvidia, openrouter"
    exit 1
    ;;
esac

# Check the API key is set
API_KEY_VALUE="${!API_KEY_VAR:-}"
if [[ -z "$API_KEY_VALUE" ]]; then
  echo "ERROR: $API_KEY_VAR is not set in .env (required for provider '$LLM_PROVIDER')"
  exit 1
fi

# ── Generate litellm_config.yaml ────────────────────────────────────
cat > "$OUTPUT" <<EOF
# Auto-generated by scripts/generate-litellm-config.sh
# Do not edit — configure LLM_PROVIDER and LLM_MODEL in .env instead.
# See litellm_config.example.yaml for reference.

model_list:
  - model_name: "*"
    litellm_params:
      model: $LLM_MODEL
      api_key: os.environ/$API_KEY_VAR

litellm_settings:
  drop_params: true
  num_retries: 3
  request_timeout: 300
EOF

echo "Generated $OUTPUT (provider=$LLM_PROVIDER, model=$LLM_MODEL)"
